name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    # Disabled due to instability issues
    if: false
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install VS Code runtime libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libasound2t64 libgbm1 libgtk-3-0t64 libnss3
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - name: Run E2E tests
        run: xvfb-run -a npm run test:e2e
  darwin:
    # Disabled due to instability issues
    if: false
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
